export const cityData = [
   {
     id:1,
     city: 'Adelaide',
     country:'Australia',
     ranking: '10',
     overallrating: '96.6',
     stability:'95',
     healthcare:'100',
     environment:'94.2',
     education:'100',
     infrastructure:'96.4',
     img: './img/adelaide.jpg'
   }, {
     id:2  ,
     city: 'Copenhagen',
     country:'Denmark',
     ranking: '9',
     overallrating: '96.8',
     stability:'95',
     healthcare:'95.8',
     environment:'95.4',
     education:'100',
     infrastructure:'100',
     img: './img/copenhagen.jpg'
   }, {
     id:3  ,
     city: 'Tokyo',
     country:'Japan',
     ranking: '7',
     overallrating: '97.2',
     stability:'100',
     healthcare:'100',
     environment:'94.4',
     education:'100',
     infrastructure:'92.9',
     img: './img/tokyo.jpg'
   }, {
     id:4  ,
     city: 'Toronto',
     country:'Canada',
     ranking: '7',
     overallrating: '97.2',
     stability:'100',
     healthcare:'100',
     environment:'97.2',
     education:'100',
     infrastructure:'89.3',
     img: './img/toronto.jpg'
   }, {
     id:5  ,
     city: 'Vancouver',
     country:'Canada',
     ranking: '6',
     overallrating: '97.3',
     stability:'95',
     healthcare:'100',
     environment:'100',
     education:'100',
     infrastructure:'92.9',
     img: './img/vancouver.jpg'
   }, {
    id:6  ,
    city: 'Calgary',
    country:'Canada',
    ranking: '5',
    overallrating: '97.5',
    stability:'100',
    healthcare:'100',
    environment:'90',
    education:'100',
    infrastructure:'100',
    img: './img/calgary.jpg'
   }, {
    id:7  ,
    city: 'Osaka',
    country:'Japan',
    ranking: '4',
    overallrating: '97.7',
    stability:'100',
    healthcare:'100',
    environment:'93.5',
    education:'100',
    infrastructure:'96.4',
    img: './img/osaka.jpg'
  }, {
    id:8  ,
     city: 'Sydney',
     country:'Australia',
     ranking: '3',
     overallrating: '98.1',
     stability:'95',
     healthcare:'100',
     environment:'94.4',
     education:'100',
     infrastructure:'100',
     img: './img/sydney.jpg'
  }, {
    id:9  ,
    city: 'Melbourne',
    country:'Australia',
    ranking: '2',
    overallrating: '98.4',
    stability:'95',
    healthcare:'100',
    environment:'98.6',
    education:'100',
    infrastructure:'100',
    img: './img/melbourne.jpg'
  }, {
    id:10,
    city: 'Vienna',
    country:'Austria',
    ranking: '1',
    overallrating: '99.1',
    stability:'100',
    healthcare:'100',
    environment:'96.3',
    education:'100',
    infrastructure:'100',
    img: './img/vienna.jpg'
  }
]
